package backup_two;
// default package
// Generated Nov 20, 2014 1:09:15 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentClassSection generated by hbm2java
 */
@Entity
@Table(name = "student_class_section", catalog = "hibernate")
public class StudentClassSection implements java.io.Serializable {

	private Integer studentClassSectionId;
	private ClassSection classSection;
	private Student student;
	private SystemUser systemUserByCreatedBy;
	private SystemUser systemUserByLastUpdatedBy;
	private Date creationTimestamp;
	private Date lastUpdatedTimestamp;

	public StudentClassSection() {
	}

	public StudentClassSection(ClassSection classSection, Student student,
			SystemUser systemUserByCreatedBy,
			SystemUser systemUserByLastUpdatedBy) {
		this.classSection = classSection;
		this.student = student;
		this.systemUserByCreatedBy = systemUserByCreatedBy;
		this.systemUserByLastUpdatedBy = systemUserByLastUpdatedBy;
	}

	public StudentClassSection(ClassSection classSection, Student student,
			SystemUser systemUserByCreatedBy,
			SystemUser systemUserByLastUpdatedBy, Date creationTimestamp,
			Date lastUpdatedTimestamp) {
		this.classSection = classSection;
		this.student = student;
		this.systemUserByCreatedBy = systemUserByCreatedBy;
		this.systemUserByLastUpdatedBy = systemUserByLastUpdatedBy;
		this.creationTimestamp = creationTimestamp;
		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_class_section_id", unique = true, nullable = false)
	public Integer getStudentClassSectionId() {
		return this.studentClassSectionId;
	}

	public void setStudentClassSectionId(Integer studentClassSectionId) {
		this.studentClassSectionId = studentClassSectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_section_id", nullable = false)
	public ClassSection getClassSection() {
		return this.classSection;
	}

	public void setClassSection(ClassSection classSection) {
		this.classSection = classSection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public SystemUser getSystemUserByCreatedBy() {
		return this.systemUserByCreatedBy;
	}

	public void setSystemUserByCreatedBy(SystemUser systemUserByCreatedBy) {
		this.systemUserByCreatedBy = systemUserByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "last_updated_by", nullable = false)
	public SystemUser getSystemUserByLastUpdatedBy() {
		return this.systemUserByLastUpdatedBy;
	}

	public void setSystemUserByLastUpdatedBy(
			SystemUser systemUserByLastUpdatedBy) {
		this.systemUserByLastUpdatedBy = systemUserByLastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_timestamp", length = 19)
	public Date getCreationTimestamp() {
		return this.creationTimestamp;
	}

	public void setCreationTimestamp(Date creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_timestamp", length = 19)
	public Date getLastUpdatedTimestamp() {
		return this.lastUpdatedTimestamp;
	}

	public void setLastUpdatedTimestamp(Date lastUpdatedTimestamp) {
		this.lastUpdatedTimestamp = lastUpdatedTimestamp;
	}

}
